function s = EmptyStep(n)
% Preallocates a step struct array with the default parameter structure.
arguments
    n (1,1) double = 0
end

template = struct( ...
    "ID",              "", ...
    "Name",            "", ...
    "Phase",           "", ...
    "Mandatory",       false, ...
    "Enabled",         false, ...
    "LastRunEnabled",  false, ...
    "GenerateFigures", false, ...
    "FigureFolder",    "", ...
    "NeedsRerun",      false, ...
    "Parameters",      GUI.EmptyParam(0),...
    "Function",        []);

if n == 0
    s = template([]);
else
    s = repmat(template, 1, n);
end
end
